# Generated by Django 5.0.1 on 2024-02-02 08:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('game_stats', models.JSONField(blank=True, default=dict, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('fields', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('img', models.ImageField(blank=True, null=True, upload_to='./media/')),
                ('details', models.TextField(max_length=500)),
                ('rules', models.TextField(max_length=500)),
                ('eventhost', models.CharField(max_length=20)),
                ('event_type', models.CharField(choices=[('knockout', 'knockout'), ('league', 'league')], default='knockout', max_length=10)),
                ('event_state', models.CharField(choices=[('active', 'active'), ('started', 'started'), ('ended', 'ended'), ('pending', 'pending')], default='active', max_length=10)),
                ('winner_reward', models.CharField(max_length=10)),
                ('runner_reward', models.CharField(max_length=10)),
                ('third_reward', models.CharField(max_length=10)),
                ('reward_type', models.CharField(choices=[('money', 'money'), ('credit', 'credit'), ('other', 'other')], max_length=10)),
                ('max_players', models.IntegerField()),
                ('eventplayers', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('runner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events_runner', to=settings.AUTH_USER_MODEL)),
                ('third', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events_third', to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events_won', to=settings.AUTH_USER_MODEL)),
                ('eventgame', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='api.game')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='joined_events',
            field=models.ManyToManyField(blank=True, default=None, to='api.event'),
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matchstate', models.CharField(choices=[('pending', 'pending'), ('ended', 'ended'), ('active', 'active')], default='pending', max_length=10)),
                ('round', models.IntegerField(blank=True, null=True)),
                ('root', models.IntegerField(blank=True, null=True)),
                ('player1stats', models.JSONField(blank=True, default=dict, null=True)),
                ('player2stats', models.JSONField(blank=True, default=dict, null=True)),
                ('matchgame', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='matches', to='api.game')),
                ('matchwinner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='matches_won', to=settings.AUTH_USER_MODEL)),
                ('player1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='matches_as_player1', to=settings.AUTH_USER_MODEL)),
                ('player2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='matches_as_player2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='matches',
            field=models.ManyToManyField(blank=True, to='api.match'),
        ),
    ]
