# Generated by Django 4.2.3 on 2023-12-30 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
