# Generated by Django 5.0.1 on 2024-02-02 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_testfield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='testfield',
        ),
    ]
