# Generated by Django 4.2.3 on 2023-12-30 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
    ]
