# Generated by Django 4.2.3 on 2024-01-20 03:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_user_first_name_user_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('eFootball', 'eFootball'), ('BGMI', 'BGMI'), ('CODM', 'CODM'), ('FREE FIRE', 'FREE FIRE')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matchgame', models.CharField(choices=[('eFootball', 'eFootball'), ('BGMI', 'BGMI'), ('CODM', 'CODM'), ('FREE FIRE', 'FREE FIRE')], max_length=15)),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='matches_as_player1', to=settings.AUTH_USER_MODEL)),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='matches_as_player2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('img', models.ImageField(blank=True, null=True, upload_to='./media/')),
                ('eventgame', models.CharField(max_length=20)),
                ('eventhost', models.CharField(max_length=20)),
                ('eventplayers', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='joined_events',
            field=models.ManyToManyField(to='api.event'),
        ),
    ]
