# Generated by Django 4.2.3 on 2024-01-20 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_game_match_event_user_joined_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='eventgame',
            field=models.CharField(choices=[('eFootball', 'eFootball'), ('BGMI', 'BGMI'), ('CODM', 'CODM'), ('FREE FIRE', 'FREE FIRE')], max_length=15),
        ),
    ]
