# Generated by Django 4.2.3 on 2024-01-20 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_event_eventgame'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='details',
            field=models.CharField(default='Event Details', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='event_state',
            field=models.CharField(choices=[('active', 'active'), ('started', 'started'), ('ended', 'ended'), ('pending', 'pending')], default='active', max_length=10),
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('knockout', 'knockout'), ('league', 'league')], default='knockout', max_length=10),
        ),
        migrations.AddField(
            model_name='event',
            name='rules',
            field=models.CharField(default='1) Rule 1 \n 2) Rule 2', max_length=500),
            preserve_default=False,
        ),
    ]
