# Generated by Django 4.2.3 on 2024-01-20 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_event_details_event_event_state_event_event_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='details',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='event',
            name='rules',
            field=models.TextField(max_length=500),
        ),
    ]
