# Generated by Django 4.2.3 on 2024-01-20 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_event_details_alter_event_rules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='eventgame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='api.game'),
        ),
        migrations.AlterField(
            model_name='match',
            name='matchgame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='matches', to='api.game'),
        ),
    ]
