# Generated by Django 4.2.3 on 2024-01-20 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_event_eventgame_alter_match_matchgame'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(max_length=15),
        ),
    ]
