# Generated by Django 4.2.3 on 2024-01-20 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_game_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='joined_events',
            field=models.ManyToManyField(default=None, to='api.event'),
        ),
    ]
