# Generated by Django 4.2.3 on 2024-01-20 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_user_joined_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='joined_events',
            field=models.ManyToManyField(blank=True, default=None, to='api.event'),
        ),
    ]
