# Generated by Django 4.2.3 on 2024-01-20 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_user_joined_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='runner_reward',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='third_reward',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='winner_reward',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
