# Generated by Django 4.2.3 on 2024-01-20 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_event_runner_reward_event_third_reward_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='reward_type',
            field=models.CharField(choices=[('money', 'money'), ('credit', 'credit')], default='credit', max_length=10),
            preserve_default=False,
        ),
    ]
