# Generated by Django 4.2.3 on 2024-01-20 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_event_reward_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='reward_type',
            field=models.CharField(choices=[('money', 'money'), ('credit', 'credit'), ('other', 'other')], max_length=10),
        ),
    ]
