# Generated by Django 4.2.3 on 2024-01-20 18:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_event_reward_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='eventplayers',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
