# Generated by Django 4.2.3 on 2024-01-21 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_event_eventplayers'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='max_players',
            field=models.IntegerField(default=16),
            preserve_default=False,
        ),
    ]
