# Generated by Django 4.2.3 on 2024-01-22 02:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_event_max_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='matches',
            field=models.ManyToManyField(blank=True, to='api.match'),
        ),
        migrations.AddField(
            model_name='match',
            name='matchstate',
            field=models.CharField(choices=[('pending', 'pending'), ('ended', 'ended')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='match',
            name='matchwinner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='matches_won', to=settings.AUTH_USER_MODEL),
        ),
    ]
