# Generated by Django 4.2.3 on 2024-01-22 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_event_matches_match_matchstate_match_matchwinner'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='round',
            field=models.IntegerField(null=True),
        ),
    ]
