# Generated by Django 4.2.3 on 2024-01-22 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_match_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='root',
            field=models.IntegerField(null=True),
        ),
    ]
