# Generated by Django 4.2.3 on 2024-01-22 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_event_root'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='root',
        ),
        migrations.AddField(
            model_name='match',
            name='root',
            field=models.IntegerField(null=True),
        ),
    ]
