# Generated by Django 4.2.3 on 2024-01-24 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_match_player1_alter_match_player2'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='game_stats',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
