# Generated by Django 4.2.3 on 2024-01-24 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_user_game_stats'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='fields',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
