# Generated by Django 4.2.3 on 2024-01-24 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_game_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='matchstate',
            field=models.CharField(choices=[('pending', 'pending'), ('ended', 'ended'), ('active', 'active')], default='pending', max_length=10),
        ),
    ]
