# Generated by Django 4.2.3 on 2024-01-24 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_alter_user_game_stats'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='player1stats',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='player2stats',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
