# Generated by Django 4.2.3 on 2024-01-24 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_match_player1stats_match_player2stats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='game_stats',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
