# Generated by Django 4.2.3 on 2024-01-26 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_alter_user_game_stats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='player1stats',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='player2stats',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
