# Generated by Django 4.2.3 on 2024-01-26 21:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_alter_match_player1stats_alter_match_player2stats'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events_won', to=settings.AUTH_USER_MODEL),
        ),
    ]
