# Generated by Django 4.2.3 on 2024-01-26 22:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_event_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='runner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events_runner', to=settings.AUTH_USER_MODEL),
        ),
    ]
