# Generated by Django 4.2.3 on 2024-01-27 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_event_runner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='root',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='round',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
