# Generated by Django 4.2.3 on 2024-01-29 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_alter_match_root_alter_match_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='third',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events_third', to=settings.AUTH_USER_MODEL),
        ),
    ]
